spring:
  jpa:
    database: MYSQl
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/diploma
    username: user
    password: danielq
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 516233876888-aiig0b308l5989keefvttcnr6t4ll2al.apps.googleusercontent.com
            client-secret: 3L--2mfgjMViShlQmrHNGZU5
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

app:
  auth:
    tokenExpirationMsec: 864000000
    token-secret: 8Zz5tw0Ionm3XPZZfN0NOml3z9FMfmpgXwovR9fp6ryDIoGRM8EPHAB6iHsc0fb
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect
server:
  port: 8080